version: '3.9'

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: vm
    command: -opentsdbHTTPListenAddr=:4242
    ports:
      - 8428:8428
      - 4242:4242
    volumes:
      - /Users/alexey/Documents/victoriametrics_set_test:/victoria-metrics-data
    environment:
      TZ: ${TIME_ZONE}
