version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIME_ZONE}
      PGDATA: '/var/lib/postgresql/data/pgdata'
      # command: postgres -c config_file=/var/lib/postgresql/data/pgdata/postgresql.conf
    # command: postgres -c max_connections=1000 -c shared_buffers=4GB
    ports:
      - 5432:5432
    volumes:
      - /Users/alexey/PycharmProjects/psql_set_test:/var/lib/postgresql/data
      # - ./config/psql/postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
