#FROM grafana/grafana-enterprise
FROM grafana/grafana-enterprise:11.1.0-ubuntu

ARG HOST=localhost

COPY config/grafana/grafana.ini /etc/grafana/
#RUN sed -i "/^domain=*/c domain=$HOST" /etc/grafana/grafana.ini
EXPOSE 3000
