# pull official base image
FROM grafana/grafana

RUN grafana-cli plugins install yesoreyeram-boomtheme-panel \
    && grafana-cli plugins install digiapulssi-breadcrumb-panel \
    && grafana-cli plugins install agenty-flowcharting-panel
