services:
  grafana:
    #build:
    #  context: ../..
    #  dockerfile: docker/docker-files/grafana/Dockerfile.grafana
    image: grafana/grafana-enterprise:10.4.4-ubuntu
    container_name: grafana
    hostname: ${HOST_GRAFANA}
    restart: unless-stopped
    environment:
      - GF_RENDERING_SERVER_URL=http://${HOST_GRAFANA_RENDERER}:${PORT_GRAFANA_RENDERER}/render
      - GF_RENDERING_CALLBACK_URL=http://${HOST_GRAFANA}:${PORT_GRAFANA}/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - ${PORT_GRAFANA}:${PORT_GRAFANA}
    
  renderer:
    image: grafana/grafana-image-renderer:latest
    hostname: ${HOST_GRAFANA_RENDERER}
    ports:
      - ${PORT_GRAFANA_RENDERER}:${PORT_GRAFANA_RENDERER}

volumes:
  grafana_storage: {}
