services:
  grafana:
    #build:
    #  context: ../..
    #  dockerfile: docker/docker-files/grafana/Dockerfile.grafana
    image: grafana/grafana-enterprise:10.4.4-ubuntu
    container_name: grafana
    hostname: ${HOST_GRAFANA}
    restart: unless-stopped
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://${HOST_GRAFANA}:3000/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - 3000:3000
    
  renderer:
    image: grafana/grafana-image-renderer:latest
    hostname: renderer
    ports:
      - 8081

volumes:
  grafana_storage: {}
