services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    hostname: ${HOST_REDIS}
    ports:
      - ${PORT_REDIS}:${PORT_REDIS}
      - ${PORT_REDIS_INSIGHT}:${PORT_REDIS_INSIGHT}
    networks:
      - peresvet
    environment:
      TZ: ${TIME_ZONE}

networks:
  peresvet:
    driver: bridge
    ipam:
      config:
          - subnet: 10.66.0.0/16
            gateway: 10.66.0.1