services:
  ldap:
    hostname: ${LDAP_HOST}
    build:
      context: ../..
      dockerfile: docker/docker-files/ldap/Dockerfile.ldap

    environment:
      TZ: ${TIME_ZONE}
      LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL}
    ports:
      - ${LDAP_PORT}:${LDAP_PORT}
    networks:
      - peresvet

networks:
  peresvet:
    driver: bridge